### ISSUE TITLE
Invalid message type: 52/53

### ISSUE THREAD

**Issue by xfk** [hugelgupf/p9#51]
I've been using the u-root/cpu command. I tried to do a "go build" while "cpu-ed" and get the following error message:
```
2022/01/30 22:45:26 unknown error: invalid message type: 52
go: RLock /home/xfk/src/cpu/go.mod: input/output error
```
or sometimes:
```
2022/01/30 22:45:26 unknown error: invalid message type: 53
go: RLock /home/xfk/src/cpu/go.mod: input/output error
```

I see those types are not implemented in this library which u-root/cpu uses. (I apologize if I reported the issue in the wrong place)

**Comment by hugelgupf** [comment]
cc @rminnich 

Looks like the T/Rlock message types https://github.com/chaos/diod/blob/master/protocol.md#lock---acquire-or-release-a-posix-record-lock

We'd never needed this in gVisor, so we never implemented it. Should be easy.

**Comment by rminnich** [comment]
Please see my latest PR.
And help me fix fuzzing ;-)

**Comment by hugelgupf** [comment]
My bad, I should be taking care of issues. https://github.com/hugelgupf/p9/pull/52 implemented this.
