### ISSUE TITLE
Handle O_NONBLOCK

### ISSUE THREAD

**Issue by Stebalien** [hugelgupf/p9#6]
O_NONBLOCK can be passed to any filesystem operation. This library should pass this flag through to the underlying implementation (or, at the very least, ignore it). As far as I can tell, it currently just returns an "invalid argument" error.

Note: This breaks `ls`.

**Comment by hugelgupf** [comment]
You have a good point. gVisor always assumed that all file system ops are non-blocking (and implemented blocking ops on top of that on the client side), so we built that assumption into the library.

**Comment by hugelgupf** [comment]
I'm looking into this right now. I don't think it's the O_NONBLOCK, but I'm having to write some debugging tools before I can figure out what it actually is.

**Comment by hugelgupf** [comment]
Turning on debug output, there ended up being two problems:

```go
2019/09/01 17:15:46 recv [conn 0xc00009e028] [Tag 000002] Twalk{FID: 1, newFID: 3, Names: []}                                                                                                   
2019/09/01 17:15:46 send [conn 0xc00009e028] [Tag 000002] Rlerror{Error: 22}
```

as the most likely cause for the `EINVAL`. Let's see where it's coming from.

(in this case, `localfs` did not allow walking to self. :/)

The other problem was indeed the flags.
