### ISSUE TITLE
localfs does not implement unlinkat

### ISSUE THREAD

**Issue by edouardklein** [hugelgupf/p9#86]
As the title says, unless I'm reading and using the code wrong, unlinkat is not implemented. Therefore there is no way to remove anything from a server served with p9ufs.

If I'm not mistaken in this, I think I'll take a shot at implementing it, but I wonder why it's not there in the first place, and so second guess myself. Maybe I've misunderstood something.

**Comment by hugelgupf** [comment]
You are... correct. Are you up for a PR? Should be another tested thing as well.

**Comment by edouardklein** [comment]
I'll try :) I may need some guidance as Go is not my usual language; if I'm in trouble I'll ask here.
